// style
import './globals.css';

// fonts
import { Inter } from 'next/font/google';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import Font Awesome styles
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

// components
import { Navbar } from './components/Navbar';
import Footer from '@/app/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Memizer',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
